library(shiny)
library(tidyverse)
library(plyr)
library(shinythemes)
library(RColorBrewer)
library(DT)
library(data.table)

CPPdta <- read_csv("C:/Users/cassidy.nicholas/OneDrive - IS/CommunityPlanningOutcomesProfiler/CPPcleandata.csv")
IGZdta <- read_csv("C:/Users/cassidy.nicholas/OneDrive - IS/CommunityPlanningOutcomesProfiler/IGZcleandata.csv")
DZdta <- read_csv("C:/Users/cassidy.nicholas/OneDrive - IS/CommunityPlanningOutcomesProfiler/DZcleandata.csv")